#
# Copyright (c) 2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/herdstat/herdstat.
#
# SPDX-License-Identifier: MIT
#

# Reference herdstat configuration file. Given values are the default values.

# Toggle for verbose output
verbose: false

# Repositories to analyze. Can be either a plain 'owner' or 'owner/repository' combination.
repositories:
  - herdstat

# Token used to access the GitHub API. If not defined requests will be made anonymously and rate limits might make
# requests fail.
github-token: ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

# Configuration for the 'contribution-graph' command
contribution-graph:

  # Date of last date to be visualized (supports many date formats)
  until: 2023-10-30

  # The name of the output SVG file
  filename: contribution-graph.svg

  # Whether the output SVG should be minified
  minify: true

  # The primary color used for coloring daily contribution cells (hex-encoded RGB without leading '#')
  color: 39D352

  # The number of color levels used for coloring contribution cells
  levels: 5

  # Filters used to exclude contributions
  filters:

    # Filters for commits
    commits:
