#
# Copyright (c) 2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/herdstat/herdstat.
#
# SPDX-License-Identifier: MIT
#

name: Release Please
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: go
          package-name: herdstat
          bump-minor-pre-major: true
          signoff: "Sven Trieflinger <sven@trieflinger.com>"